# Generated by Django 3.0.6 on 2024-06-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0013_auto_20200611_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomanceMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='romance_movies/')),
                ('hyperlink', models.URLField()),
            ],
        ),
    ]
